### ISSUE TITLE
Impossible to start service ?

### ISSUE THREAD

**Issue by RomyxBaps** [geerlingguy/docker-debian10-ansible#10]
Hi,

First of all thank you for your incredible work.
Here is my problem, i try to install docker on docker with your image and the service won't start with this errors :
`Failed to connect to bus: No such file or directory   `

I try to create my own image with a new line but withotu success : 
`CMD ["/sbin/init"]`

Where is my error or is it normal ?

**Comment by wargfn** [comment]
Can you post your Dockerfile or command line that you are building the image with? And are you trying to bring it up via the command line or docker compose? Would also be helpful to either post your command line or docker-compose file.

**Comment by RomyxBaps** [comment]
Here is my docker file : 

```
FROM debian:buster
LABEL maintainer="Jeff Geerling"

ENV DEBIAN_FRONTEND noninteractive

ENV pip_packages "ansible cryptography"

# Install dependencies.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       sudo systemd systemd-sysv \
       build-essential wget libffi-dev libssl-dev \
       python3-pip python3-dev python3-setuptools python3-wheel \
       gnupg python3 python3-dev gcc git curl autoconf automake python3-cryptography \ 
       musl-dev libffi-dev libssl-dev libcurl4-openssl-dev openssh-server apt-transport-https \
       ca-certificates curl gnupg-agent software-properties-common sudo \
    && rm -rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && apt-get clean \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add - \
    && sudo apt-key fingerprint 0EBFCD88 \
    && sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
    && apt-get update \ 
    && apt-get install -y docker-ce docker-ce-cli containerd.io

# Install Ansible via pip.
RUN pip3 install $pip_packages

COPY initctl_faker .
RUN chmod +x initctl_faker && rm -fr /sbin/initctl && ln -s /initctl_faker /sbin/initctl

# Install Ansible inventory file.
RUN mkdir -p /etc/ansible
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

# Make sure systemd doesn't start agettys on tty[1-6].
RUN rm -f /lib/systemd/system/multi-user.target.wants/getty.target

VOLUME ["/sys/fs/cgroup"]
CMD ["/lib/systemd/systemd"]
CMD ["/sbin/init"]
```

The command to start docker is launch when i'm in with a terminal.
I build my image with CLI.

**Comment by wargfn** [comment]
I dont think you can have two commands running at the same time in the docker container.  Pretty sure Docker expects to see just one CMD line that the container uses to see if it is running. Is there something you are looking to gain calling /sbin/init?

**Comment by RomyxBaps** [comment]
Hmmm i don't really know.
All i want is to have the opportunity to launch a 'service' command like 'service docker start'.

I'm new in docker and building image, i don't have all the knowledge i want on it :/

**Comment by wargfn** [comment]
Did you miss a FROM debian:buster in your pasting the Dockerfile?

**Comment by RomyxBaps** [comment]
Yeah the code didn't show entierly. I edit it

**Comment by wargfn** [comment]
I am trying to build your version right now. I was able to successfully start the container with two CMD lines.  You could just run this command to start the container:
docker run --detach --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro geerlingguy/docker-debian10-ansible:latest
then this command to attach to it to install docker in it:
docker exec --tty [container_id] env TERM=xterm ansible --version

**Comment by wargfn** [comment]
Well, the container built and CONTAINER ID        IMAGE                                        COMMAND                  CREATED             STATUS                  PORTS                                              NAMES
048f8e2e4112        ansible_test:1.1                             "/sbin/init"             44 seconds ago      Up 44 seconds                                                              jovial_comes up and runs on my machine (Skull Canyon x64 Debain Buster base os)

and is running at the init. Want to see if you ahve any helpful logs at:
docker container logs {container id} ?

**Comment by RomyxBaps** [comment]
I try with your command line and i can launch "service docker start" in it but with my GUI (Synology under it), when i create my container with my image freshly builded, the command is not possible.

I will take a look why 🤔

**Comment by RomyxBaps** [comment]
Just a simple question, with the dockerfile from this repo (geerlingguy), is it possible to launche a molecule container insisde it ?
Because what I want is to push a change on my gitlab to my gitlab-ce and launche a pipeline who gonna test my code inside the image debian-ansible-10 with molecule.

**Comment by rmsc** [comment]
@RomyxBaps did you solve your problem?

I'm having a similar issue with the simplest systemd commands.

This is inside a podman container, created using ansible molecule:
```
$ mol login
# loginctl enable-linger container
Failed to connect to bus: No such file or directory
```
