### ISSUE TITLE
Autobild is not working as documented

### ISSUE THREAD

**Issue by fgierlinger** [geerlingguy/docker-debian10-ansible#11]
The documentation states, that a build should be triggered whenever the base image gets updated.

> This image is built on Docker Hub automatically any time the upstream OS container is rebuilt

Just recently I found out, while setting up an auto build myself, that the trigger works only for non-official Docker images. I found this hint only on the info-sign directly in the auto build config form.

> Trigger a build in this repository whenever the base image is updated on Docker Hub. Only works for non-official images.
>
> Base images are specified in the FROM: directive in the Dockerfile of the source repository.

Since this image is derived from Debian:latest, which is an official docker image, the docker-debian10-ansible image never gets automatically rebuild.

The fix for this is rather easy: move to a scheduled build. Either on Docker Hub or via GitHub actions. The question is, how often should the container be rebuild? Once a week?

**Comment by geerlingguy** [comment]
I think the best solution for this will be to switch to GitHub Actions, and build at least weekly.

I have already moved over my Ubuntu container builds, and it has a nice side-effect; the buildx GitHub Action allows me to easily build an arm64 version of the image too!
