### ISSUE TITLE
loginctl: Failed to connect to bus: No such file or directory

### ISSUE THREAD

**Issue by rmsc** [geerlingguy/docker-debian10-ansible#15]
Using molecule-podman to test a new role, calling `loginctl` fails:

```
$ mol login --host test-debian-buster
INFO     Running default > login
root@test-debian-buster:/# loginctl
Failed to create bus connection: No such file or directory
```

The same command works fine in `docker.io/geerlingguy/docker-ubuntu2004-ansible`:

```
mol login --host test-ubuntu-focal
INFO     Running default > login
root@test-ubuntu-focal:/# loginctl
No sessions.
```

**Comment by mhdan** [comment]
I'm facing the same issue, any updates about it?

**Comment by geerlingguy** [comment]
Does it work on the docker-debian11-ansible container? Could be an issue with cgroupsv2 depending on your host OS.

**Comment by mhdan** [comment]
> Does it work on the docker-debian11-ansible container? Could be an issue with cgroupsv2 depending on your host OS.

no, the issue persists on both debian10 and debian11. my host OS is ubunutu20.04.
if the issue is related to cgroupv2, is there any solution to this problem?

**Comment by geerlingguy** [comment]
Does anything in this issue help? https://github.com/geerlingguy/docker-debian11-ansible/issues/4

**Comment by mhdan** [comment]
> root@test-debian-buster:/# loginctl
> Failed to create bus connection: No such file or directory

I have systems running in the container without any problem but the problem exists with `loginctl`.

**Comment by rmsc** [comment]
Debian 10 is now EOL, closing.
