### ISSUE TITLE
Can't find sysctl

### ISSUE THREAD

**Issue by t2d** [geerlingguy/docker-debian10-ansible#2]
Thank you for providing these great images. Somehow, TravisCI can't find `sysctl` in buster: 
```
 fatal: [instance]: FAILED! => {"changed": false, "msg": "Failed to find required executable sysctl in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}
```
See https://travis-ci.org/systemli/ansible-role-dovecot/jobs/588931530#L469
It's fine in the older releases: https://travis-ci.org/systemli/ansible-role-dovecot/builds/588931529
Everything is also fine, when running the same in a Debian Buster Vagrant box.

**Comment by geerlingguy** [comment]
Weird. I wonder if it was the update to Debian 10.1 recently; it might be an issue with the build in the upstream Debian 10 library image (see https://github.com/debuerreotype/docker-debian-artifacts/issues/new).

**Comment by t2d** [comment]
Upstream thinks it's a feature
https://github.com/debuerreotype/docker-debian-artifacts/issues/20

**Comment by vitabaks** [comment]
I have the same error during the test with Molecule
```
TASK [haproxy : Make sure the kernel parameter "net.ipv4.ip_nonlocal_bind" are enabled] ***
  fatal: [10.172.0.20]: FAILED! => {"changed": false, "msg": "Failed to find required executable \"sysctl\" in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}
```

debian10 and debian11

**Comment by vitabaks** [comment]
cc @geerlingguy

**Comment by geerlingguy** [comment]
See: https://github.com/debuerreotype/docker-debian-artifacts/issues/20 — can you provide more background about the need for it? (I don't think any of my own role's tests are failing due to it going missing...)

**Comment by vitabaks** [comment]
> can you provide more background about the need for it?

For test this code
https://github.com/vitabaks/postgresql_cluster/blob/master/roles/haproxy/tasks/main.yml#L315 

While I had to add ignore_errors

molecule workflow:
https://github.com/vitabaks/postgresql_cluster/blob/master/.github/workflows/molecule.yml#L22

**Comment by vitabaks** [comment]
> See: debuerreotype/docker-debian-artifacts#20 

That is, I need to add the installation of the procps package to [converge.yml](https://github.com/vitabaks/postgresql_cluster/blob/master/molecule/default/converge.yml)?

**Comment by geerlingguy** [comment]
For now, that'd probably be the best solution.

**Comment by vitabaks** [comment]
@geerlingguy  Thank you, I will try it.
