### ISSUE TITLE
Move to python3 interferes with Molecule idempotence test

### ISSUE THREAD

**Issue by jsf9k** [geerlingguy/docker-debian10-ansible#6]
Hello again, @geerlingguy!

After your quick resolution of #5 I realized that [my Molecule builds are still failing](https://github.com/cisagov/ansible-role-docker/pull/12/checks?check_run_id=475623672), but now for a different reason.  They fail the idempotence check because Ansible detects Python 3.7/Pip 3 the first time it is run and Python 2.X/Pip 2 the second.  Here is how it happens:

1. Note that [Ansible's Python interpreter discovery logic has changed in recent releases](https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html).
2. When Ansible runs the first time it correctly determines that `/usr/bin/python3.7` and `/usr/bin/pip3` are present but `/usr/bin/python` and `/usr/bin/pip` are not, and so it uses Python 3/Pip 3.
3. Ansible (via Molecule) installs the Ansible role I am testing, which (through that role's chain of dependencies) causes the `python-dev` and `python-pip` packages to be installed.
4. On Buster the default Python is still 2.X, and so this install causes `/usr/bin/python` and `/usr/bin/pip` (which point to Python 2.X and Pip 2, respectively) to be created.
5. When Ansible is run the second time, to test my Ansible role's idempotence, it determines that `/usr/bin/python` and `/usr/bin/pip` are present and uses them.
6. This means that any packages installed via `pip3` the first time around are now reinstalled via `/usr/bin/pip`.  This makes a difference for some packages, and therefore results in the idempotence check failing.

I verified that rebuilding this image but instead installing the packages `python-pip`, `python-dev`, `python-setuptools`, and `python-wheel` completely fixes this issue.

I think that installing only Python 3/Pip 3 in Buster is premature, since Python 2/Pip 2 is still the default for a Buster system.  I think other folks who use your images for Molecule testing will run into the same problem I did.  Is there any chance of reverting the jump to Python 3 for this Docker image?  (If not then I can just create my own fork for my purposes.)

**Comment by jsf9k** [comment]
Ignoring my own Molecule-related idempotence woes, I think the fact that Python 2 is the default Python on Buster (it's the one that gets installed to `/usr/bin/python`) should be sufficient reason not to move to Python 3 in this `Dockerfile`.

**Comment by geerlingguy** [comment]
@jsf9k - I haven't been having issues with this Debian 10 image and my playbooks / roles in Molecule. However, as I've done for my other recent images, I've updated this one to have a `python2` branch for anyone who is not ready to update their code to make sure it's working correctly with Python 3.

**Comment by jsf9k** [comment]
Thanks!  I didn't know about the python2 Docker image. That will work perfectly for my purpose.
