### ISSUE TITLE
python3-apt package is missing

### ISSUE THREAD

**Issue by jurim76** [geerlingguy/docker-debian10-ansible#9]
Molecule complains about missing python3-apt package while installing packages from role's tasks. Is it possible to add python3-apt package to Dockerfile?

**Comment by trompette** [comment]
Same here:

```
[WARNING]: Updating cache and auto-installing missing dependency: python3-apt
```

**Comment by fourstepper** [comment]
Is `python3-apt` present on a minimal netinstall of a Debian system?
